name: Repo Dispatcher
on:
  workflow_dispatch:
    #ref: refs/heads/main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Compile
          run: |
            curl \
            -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/6258556/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.SEC_TOKEN }}" \
            -d '{"ref": "main", "inputs": {"device": "r2s"}}'
